{% set name = "pyinterpolate" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinterpolate-{{ version }}.tar.gz
  sha256: c3495d93194c3761ecc9fbfa93ae19ab29116b58092b502bf6a6cdc76821ed96

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - tqdm
    - descartes
    - prettytable
    - rtree
    - pyogrio
    - geopandas
    - pandas
    - scipy
    - dask-core
    - numpy
    - matplotlib-base
    - shapely
    - pyarrow
    - pylibtiff >=0.6.1
    - deprecation

test:
  imports:
    - pyinterpolate

about:
  home: https://github.com/DataverseLabs/pyinterpolate
  summary: Spatial Interpolation in Python
  dev_url: https://github.com/DataverseLabs/pyinterpolate
  license: BSD-3-Clause
  license_file: license.txt

extra:
  recipe-maintainers:
    - SimonMolinsky
